{{/*
Make this file only relevant if we want to deploy an 
OpenDJ container for OpenText Directory Services as part of this Helm Chart:
*/}}
{{- if eq .Values.enabled true }}

########################################################################
# OpenDJ Kubernetes Secrets
########################################################################
apiVersion: v1
kind: Secret
metadata:
{{- if eq .Values.global.otdsUseReleaseName true }}
  name: {{ printf "%s-%s" .Release.Name .Chart.Name }}-secrets
{{- else }}
  name: {{ .Chart.Name }}-secrets
{{- end }}
{{- if .Values.global.namespace }}
  namespace: {{ .Values.global.namespace }}
{{- end }}
  labels:
    {{- include (printf "%s%s" .Chart.Name ".labels" ) . | nindent 4 }}
type: Opaque
data:
  OPENDJ_PASS: {{ .Values.password | b64enc }}
  OTDS_PASS: {{ .Values.otadminPassword | b64enc }}
---

{{- end }}
