  apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: otds-bec
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 4
    healthyThreshold: 1
    unhealthyThreshold: 10
    type: HTTP
    requestPath: /otdsws/rest/systemconfig/hello
    port: 8080