########################################################################
# Settings for OpenDJ
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
########################################################################

## enabled controls if OTDS backend gets deployed as a container in
## Kubernetes. If you have OTDS or OpenDJ deployed somewhere else you
## can set it to false.
enabled: true
## serviceName defines the name of the Kubernetes service for OpenDJ:
serviceName: opendj
## serviceType defines the type of the Kubernetes service for OpenDJ:
serviceType: ClusterIP
## hostname defines the hostname of the Kubernetes container for
## OpenDJ (inside the stateful set definition):
hostname: opendj
## replicas for OpenDJ:
replicas: 1
## password of the OpenDJ Directory Manager account. Note that if persisting
## data the initial password option will only have an impact on the first run
## that populates the volume.
password: otds
## otadminPassword is the password of the otadmin@otds.admin user for OTDS
## Note that if persisting data the initial password option will only have
## an impact on the first run that populates the volume.
otadminPassword: otds
## fsGroup defines the group ID in Linux that the OpenDJ Docker container
## runs in and that the volumes are mounted with.
## Normally you don't want to change it!
fsGroup: 1000
## legacyOtdsData should be enabled if using data originally from an OTDS container
legacyOtdsData: false
## waitForData should be enabled if data is being migrated from another container
waitForData: false
## jvmMemory sets the maximum amount of memory used by the otds-opendj JVM
## If this value is not set, the JVM memory will be set to 50% of
## resources.limits.memory if available otherwise 1.5GB
## Memory amounts in M, Mi, G or Gi are supported
jvmMemory:
## backup.* defines the configuration for scheduled backups of the OpenDJ data
backup:
  ## enable should be set to true enabled if backups are desired 
  enable: false
  ## schedule defines a cron schedule which determines how frequently backups
  ## will be performed.  The value "0 0 * * *" will perform backups daily at
  ## midnight.  A schedule must be defined for backups to be performed.
  schedule: "0 0 * * *"
  ## customDirectory defines a specified for the backup location.  The default
  ## will be in the bak directory of the opendj data directory.
  ## /opt/opendj/data/bak if legacyOtdsData is false
  ## /opt/otds/opendj/bak if legacyOtdsData is true
  customDirectory:
  ## sidecarImage defines the additional container image that will be added to the
  ## opendj pod to allow sending backups to cloud storage.
  ## A built image is not included, a sample set of files which can be customized
  ## and used to built an image is included with the opendj chart.
  ## Note that a full image tage needs to be specified, such as the following
  ## docker.registry.domain.local/sample-backup:latest
  sidecarImage: "docker.registry.domain.local/sample-backup:latest"
  ## sidecarCredSecret defines a secret to be mounted within the backup container.
  ## For this value to be used, sidecarCredSecretPath must also be defined
  ## Note that this secret must already exist 
  sidecarCredSecret:
  ## sidecarCredSecretPath defines the path within the backup container where
  ## the secret in sidecarCredSecret will be mounted
  ## The sample sidecar uses a secret containing a key.json file with the user key
  sidecarCredSecretPath: 
  ## sidecarEnv defines the set of environment variables to be used by the backup
  ## container.  Those needed by the sample container are included as an example
  ## The sample sidecar mounts the secret at /certs
  sidecarEnv: |
    - name: GCLOUD_PROJECT
      value: gcp_project
    - name: GCLOUD_BUCKET
      value: gcp_bucket
    - name: SLEEPTIME
      value: "3600"
    - name: BAK_SRC
      value: "/opt/opendj/data/bak"
  ## dailyArchive should be enabled if daily archives of backup data should be 
  ## created.  The archive will contain the backup data from the day, the
  ## backup directories will be wiped after the archive is created.
  dailyArchive: false
  ## archiveTime should be set to the UTC time that the archive should occur
  archiveTime: "23:30"
  ## keepArchives should be set to the number of daily archives to keep
  keepArchives: 15
## image.* defines Docker image location, tags and pull parameters for
## OpenDJ - you need to adjust this:
image:
  source: registry.opentext.com
  name: otds-opendj
  tag: 21.2.0
  pullPolicy: Always
  pullSecret:
## resource.* define the resource requirements for OpenDJ:
resources:
  enabled: true
  requests:
    cpu: 0.5
    memory: 2Gi
  limits:
    cpu: 2
    memory: 3Gi
  ## storage defines the storage size for the OpenDJ data volume:
  storage: 20G
  ## storageClassName defines the Kubernetes storage class for the
  ## OpenDJ volume:
  storageClassName:
