apiVersion: v1
kind: ConfigMap
metadata:
  name: otenv-configmap
  namespace:  {{ .Values.global.namespace }}
data:
  
{{- range $key, $val := .Values.configmap }}
  {{ $key }}: |-
{{ $val | indent 4 }}
{{- end }}
{{- if .Values.global.encryptionKey }}
  ENCRYPTION_KEY_IMPLEMENTATION_CLASS: "com.artesia.common.encryption.key.FileSystemSecretKey"
  ENCRYPTION_KEY_FILE_PATH: /opt/etc/key/key.txt
{{- end }}

