apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otds-ingress
  namespace: {{ .Values.global.namespace }}
spec:
  rules:
    - host: {{ .Values.otdsws.publicHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.otdsws.serviceName }}
                port:
                  number: {{ .Values.otdsws.port }}
