# Define the replicas and resources for a small OTMM container deployment
#  -- SMALL PRODUCTION Standard --
#

storage:
  adaptivemedia: 10Gi
  database: 15Gi
  digitalhub: 10Gi
  otmmRepository: 415Gi
  search: 16Gi
  staging: 188Gi
  dmts: 38Gi
  kahadb: 10Gi
  rabbitmq: &rabbitmq_storage 500Mi
  
memory:
  otmm: 10Gi
  indexer: 2Gi
  search: 6Gi
  dmts:
    service: 1Gi
    image: 4.5Gi
    video: 4.5Gi
  adaptivemedia: 2Gi
  digitalhub: 3Gi
  filetransfer: 1Gi
  mediaanalysis: 1Gi
  supportmgr: 500Mi
  streaming: 1Gi
  rabbitmq: &rabbitmq_memory 1Gi
  
cpu:
  otmm: 2
  indexer: 200m
  search: 1
  dmts:
    service: 200m
    image: 1
    video: 1
  adaptivemedia: 300m
  digitalhub: 1.3
  filetransfer: 400m
  mediaanalysis: 200m
  supportmgr: 100m
  streaming: 200m
  rabbitmq: &rabbitmq_cpu 200m
  
replicaCount:
  default: 1
  adaptivemedia: 0
  otmm: 1
  dmts:
    service: 1
    image: 1
    video: 1
  searchSecondary: 1
  digitalhub: 0
  mediaanalysis: 1
  filetransfer: 1

javaOptions:
  otmmjvmopts: -Xms4g -Xmx10g -Dcom.amazonaws.sdk.disableCertChecking=true
  indexjvmopts: -Xms1024m -Xmx2048m
  searchjvmopts: -Xms2048m -Xmx6g
  dmts:
    imagejvmopts: -Xms2048m -Xmx4500m
    videojvmopts: -Xms2048m -Xmx4500m
    servicejvmopts: -Xms2048m -Xmx2048m
  amdjvmopts: -Xms1024m -Xmx2048m
  dhubjvmopts: -Xms1024m -Xmx3g
  rmajvmopts: -Xms1024m -Xmx2048m
  supportjvmopts: -Xms512m -Xmx512m

rabbitmq:
  resources:
    requests:
      cpu: *rabbitmq_cpu
      memory: *rabbitmq_memory
    storage: *rabbitmq_storage
